version: "3.7"

networks:
    php-net:
        driver: bridge

services:
    app:
        build:
            args:
                user: dev
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        ports:
            - 80:80
        image: php-app
        container_name: php-application
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html
        networks:
            - php-net 
    
    db:
        image: mysql:8.0.32
        container_name: php-db
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: passwd 
            MYSQL_DATABASE: appdb
            MYSQL_PASSWORD: passwd 
            MYSQL_USER: user 
        networks:
            - php-net   	
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 9000:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - MYSQL_ROOT_PASSWORD=passwd
            - MYSQL_PASSWORD=passwd
            - PMA_USER=root
            - PMA_PASSWORD=passwd
        networks:
            - php-net

